# docker-compose.yml
version: "3.8"

services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: accidentiq-db
    environment:
      POSTGRES_DB: accidentiq
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: accidentiq-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
